/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.rental.views;

/**
 *
 * @author ASUS
 */
public class FTransaksi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FTransaksi.class.getName());

    /**
     * Creates new form FTransaksi
     */
    public FTransaksi() {
        initComponents();

    
    // 2. Buat layar langsung Full Screen / Maximized
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    // 3. Panggil panel default kamu agar layar bawah tidak kosong (opsional)
    tblContainer.removeAll();
    tblContainer.add(new pnlListRental(), java.awt.BorderLayout.CENTER);
    tblContainer.revalidate();
    tblContainer.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        toRental = new javax.swing.JButton();
        toTambahRental = new javax.swing.JButton();
        toPengembalian = new javax.swing.JButton();
        tblContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(21, 100, 60));

        jLabel1.setBackground(new java.awt.Color(21, 100, 60));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rental Barang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        toRental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toRental.setText("List Rental");
        toRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toRentalMouseClicked(evt);
            }
        });
        toRental.addActionListener(this::toRentalActionPerformed);

        toTambahRental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toTambahRental.setText("Tambah Rental");
        toTambahRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toTambahRentalMouseClicked(evt);
            }
        });
        toTambahRental.addActionListener(this::toTambahRentalActionPerformed);

        toPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toPengembalian.setText("Pengembalian");
        toPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toPengembalianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(toRental)
                .addGap(18, 18, 18)
                .addComponent(toTambahRental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toPengembalian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toRental)
                    .addComponent(toTambahRental)
                    .addComponent(toPengembalian))
                .addGap(14, 14, 14))
        );

        tblContainer.setBackground(new java.awt.Color(255, 255, 255));
        tblContainer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tblContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tblContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toRentalActionPerformed

    private void toTambahRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTambahRentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toTambahRentalActionPerformed

    private void toRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toRentalMouseClicked
        tblContainer.removeAll(); // Bersihkan kontainer
    
    // Panggil nama class JPanel-mu (misal: PanelRental)
    pnlListRental panelList = new pnlListRental(); 
    
    tblContainer.add(panelList, java.awt.BorderLayout.CENTER); // Masukkan panel
    tblContainer.revalidate(); // Render ulang
    tblContainer.repaint();
    }//GEN-LAST:event_toRentalMouseClicked

    private void toTambahRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toTambahRentalMouseClicked
        tblContainer.removeAll();
    
    // Panggil class JPanel tambah rental
    pnlTambahRental panelTambah = new pnlTambahRental();
    
    tblContainer.add(panelTambah, java.awt.BorderLayout.CENTER);
    tblContainer.revalidate();
    tblContainer.repaint();
    }//GEN-LAST:event_toTambahRentalMouseClicked

    private void toPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toPengembalianMouseClicked
        tblContainer.removeAll();
    
    // Panggil class JPanel pengembalian
    pnlPengembalian panelKembali = new pnlPengembalian();
    
    tblContainer.add(panelKembali, java.awt.BorderLayout.CENTER);
    tblContainer.revalidate();
    tblContainer.repaint();
    }//GEN-LAST:event_toPengembalianMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FTransaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel tblContainer;
    private javax.swing.JButton toPengembalian;
    private javax.swing.JButton toRental;
    private javax.swing.JButton toTambahRental;
    // End of variables declaration//GEN-END:variables
}
