/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modules.rental.views;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import config.DatabaseConfig;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class pnlListRental extends javax.swing.JPanel {

    /**
     * Creates new form pnlListRental
     */
    public pnlListRental() {
        initComponents();
        tampilDataRental();
    }
    
   private void styleTable(javax.swing.JTable table) {
    // 1. Styling Baris dan Grid (Tampilan Clean/Flat)
    table.setRowHeight(35); // Bikin baris lebih tinggi agar tidak sempit
    table.setShowVerticalLines(false); // Hilangkan garis vertikal
    table.setShowHorizontalLines(true); // Biarkan garis horizontal sebagai pemisah
    table.setGridColor(new java.awt.Color(230, 230, 230)); // Warna garis horizontal abu-abu tipis
    table.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    
    // 2. Warna saat baris diklik (Hijau Muda)
    table.setSelectionBackground(new java.awt.Color(204, 255, 204)); 
    table.setSelectionForeground(new java.awt.Color(0, 0, 0)); // Teks tetap hitam saat dipilih

    // 3. Styling Header (Warna hijau gelap sesuai tema UI-mu)
    javax.swing.table.JTableHeader header = table.getTableHeader();
    header.setBackground(new java.awt.Color(21, 100, 60)); // Background hijau
    header.setForeground(java.awt.Color.BLACK); // Teks putih
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); // Font modern
    
    // Bikin header lebih tinggi sedikit
    header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));
    
    // Rata tengah untuk teks header
    ((javax.swing.table.DefaultTableCellRenderer)header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
            
    // Opsional: Membuat isi sel tabel rata tengah
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment( javax.swing.JLabel.CENTER );
    for(int x=0; x < table.getColumnCount(); x++){
         table.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
    }
}
    
    private Connection getKoneksi() {
        Connection conn = DatabaseConfig.getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Gagal! Pastikan MySQL/XAMPP sudah berjalan.");
        }
        return conn;
    }
    
    private void tampilDataRental() {
    // 1. Definisikan header kolom tabel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Transaksi");
    model.addColumn("Nama Customer");
    model.addColumn("Tgl. Pinjam");
    model.addColumn("Grand Total");
    model.addColumn("Status");
    
    // Set model ke komponen tblRental yang sudah dibuat di Netbeans
    tblRental.setModel(model);
    styleTable(tblRental);
    
    try {
        Connection conn = getKoneksi();
        Statement stmt = conn.createStatement();
        
        // 2. Query JOIN untuk mendapatkan nama lengkap dari tabel customers
        String sql = "SELECT r.id_rental, c.nama_lengkap, r.tgl_pinjam, r.total_harga, r.status_rental " +
                     "FROM rentals r " +
                     "JOIN customers c ON r.id_customer = c.id_customer " +
                     "ORDER BY r.id_rental DESC";
                     
        ResultSet rs = stmt.executeQuery(sql);
        
        // 3. Looping data dari database ke dalam row tabel
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_rental"),
                rs.getString("nama_lengkap"),
                rs.getString("tgl_pinjam"),
                rs.getString("total_harga"),
                rs.getString("status_rental")
            });
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data rental: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tableContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrRental = new javax.swing.JScrollPane();
        tblRental = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        tableContainer.setBackground(new java.awt.Color(248, 255, 252));

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("List Rental Barang");

        tblRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Nama Customer", "Tgl. Pinjam", "Grand Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRentalMouseClicked(evt);
            }
        });
        scrRental.setViewportView(tblRental);

        jButton1.setText("Cetak Excel");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout tableContainerLayout = new javax.swing.GroupLayout(tableContainer);
        tableContainer.setLayout(tableContainerLayout);
        tableContainerLayout.setHorizontalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(scrRental, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        tableContainerLayout.setVerticalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableContainerLayout.createSequentialGroup()
                .addGroup(tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableContainerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrRental, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRentalMouseClicked

    }//GEN-LAST:event_tblRentalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Membuka jendela dialog agar user bisa milih lokasi save file
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Simpan Laporan Excel");
    
    // Set default nama file (misal: Laporan_Bulanan.xlsx)
    fileChooser.setSelectedFile(new java.io.File("Laporan_Bulanan.xlsx"));

    int userSelection = fileChooser.showSaveDialog(this);

    // 2. Jika user menekan tombol "Save" di dialog
    if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File fileToSave = fileChooser.getSelectedFile();
        
        // Pastikan formatnya berakhiran .xlsx
        String filePath = fileToSave.getAbsolutePath();
        if(!filePath.toLowerCase().endsWith(".xlsx")) {
            fileToSave = new java.io.File(filePath + ".xlsx");
        }

        try {
            // 3. Panggil class Utility Excel kita
            // Asumsi tabel kamu bernama 'tableReport' atau 'customerList'
            utils.ExcelExporter exporter = new utils.ExcelExporter();
            exporter.exportTable(tblRental, fileToSave); // Ganti tableReport dengan nama JTable-mu
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Berhasil mengekspor data ke Excel!\nLokasi: " + fileToSave.getAbsolutePath(), 
                "Sukses", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal menyimpan file: " + ex.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrRental;
    private javax.swing.JPanel tableContainer;
    private javax.swing.JTable tblRental;
    // End of variables declaration//GEN-END:variables
}
