/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modules.rental.views;

// Importan
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import config.DatabaseConfig;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class pnlPengembalian extends javax.swing.JPanel {

    /**
     * Creates new form pnlPengembalian
     */
    public pnlPengembalian() {
        initComponents();
        tampilDataDipinjam();
    }
    
    private void styleTable(javax.swing.JTable table) {
    // 1. Styling Baris dan Grid (Tampilan Clean/Flat)
    table.setRowHeight(35); // Bikin baris lebih tinggi agar tidak sempit
    table.setShowVerticalLines(false); // Hilangkan garis vertikal
    table.setShowHorizontalLines(true); // Biarkan garis horizontal sebagai pemisah
    table.setGridColor(new java.awt.Color(230, 230, 230)); // Warna garis horizontal abu-abu tipis
    table.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    
    // 2. Warna saat baris diklik (Hijau Muda)
    table.setSelectionBackground(new java.awt.Color(204, 255, 204)); 
    table.setSelectionForeground(new java.awt.Color(0, 0, 0)); // Teks tetap hitam saat dipilih

    // 3. Styling Header (Warna hijau gelap sesuai tema UI-mu)
    javax.swing.table.JTableHeader header = table.getTableHeader();
    header.setBackground(new java.awt.Color(21, 100, 60)); // Background hijau
    header.setForeground(java.awt.Color.BLACK); 
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); // Font modern
    
    // Bikin header lebih tinggi sedikit
    header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));
    
    // Rata tengah untuk teks header
    ((javax.swing.table.DefaultTableCellRenderer)header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
            
    // Opsional: Membuat isi sel tabel rata tengah
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment( javax.swing.JLabel.CENTER );
    for(int x=0; x < table.getColumnCount(); x++){
         table.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
    }
}
    
    // --- METHOD KONEKSI ---
    private Connection getKoneksi() {
        Connection conn = DatabaseConfig.getConnection();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Gagal! Pastikan MySQL/XAMPP sudah berjalan.");
        }
        return conn;
    }   
    
    // --- METHOD TAMPIL DATA ---
    private void tampilDataDipinjam() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Customer");
        model.addColumn("Tgl. Pinjam");
        model.addColumn("Grand Total");
        model.addColumn("Status");
        
        tblHapusRental.setModel(model);
        styleTable(tblHapusRental);
        
        try {
            Connection conn = getKoneksi();
            Statement stmt = conn.createStatement();
            
            // Query JOIN hanya untuk status_rental = 'Dipinjam'
            String sql = "SELECT r.id_rental, c.nama_lengkap, r.tgl_pinjam, r.total_harga, r.status_rental " +
                         "FROM rentals r " +
                         "JOIN customers c ON r.id_customer = c.id_customer " +
                         "WHERE r.status_rental = 'Dipinjam' " +
                         "ORDER BY r.id_rental ASC";
                         
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_rental"),
                    rs.getString("nama_lengkap"),
                    rs.getString("tgl_pinjam"),
                    rs.getString("total_harga"),
                    rs.getString("status_rental")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tableContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        scrHapusRental = new javax.swing.JScrollPane();
        tblHapusRental = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnHapusRental = new javax.swing.JButton();

        tableContainer.setBackground(new java.awt.Color(248, 255, 252));

        jLabel2.setBackground(new java.awt.Color(0, 153, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Pengembalian Barang");

        tblHapusRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Nama Customer", "Tgl. Pinjam", "Grand Total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrHapusRental.setViewportView(tblHapusRental);

        jLabel3.setBackground(new java.awt.Color(0, 153, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Pengembalian dilakukan dillakukan Pengecekan dan Stok akan terupdate otomatis!");

        btnHapusRental.setBackground(new java.awt.Color(0, 153, 51));
        btnHapusRental.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusRental.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusRental.setText("Kembalikan Barang ke Stok");
        btnHapusRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusRentalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapusRental, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapusRental, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tableContainerLayout = new javax.swing.GroupLayout(tableContainer);
        tableContainer.setLayout(tableContainerLayout);
        tableContainerLayout.setHorizontalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrHapusRental)
            .addGroup(tableContainerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tableContainerLayout.setVerticalGroup(
            tableContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableContainerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrHapusRental, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusRentalMouseClicked
        int row = tblHapusRental.getSelectedRow();

        // Validasi apakah ada baris yang dipilih
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data rental yang ingin dikembalikan terlebih dahulu!");
            return;
        }

        String idRentalStr = tblHapusRental.getValueAt(row, 0).toString();
        String namaCustomer = tblHapusRental.getValueAt(row, 1).toString();
        int idRental = Integer.parseInt(idRentalStr);

        // Memunculkan OptionPane Konfirmasi
        int pilihan = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menyelesaikan transaksi rental ID: " + idRental + " atas nama " + namaCustomer + "?\nStok barang akan dikembalikan otomatis.",
            "Konfirmasi Pengembalian",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (pilihan == JOptionPane.YES_OPTION) {
            try {
                Connection conn = getKoneksi();
                conn.setAutoCommit(false); // Mulai Transaksi Database

                // 1. Update status_rental menjadi 'Selesai' di tabel rentals
                String sqlUpdateStatus = "UPDATE rentals SET status_rental = 'Selesai' WHERE id_rental = ?";
                PreparedStatement pstStatus = conn.prepareStatement(sqlUpdateStatus);
                pstStatus.setInt(1, idRental);
                pstStatus.executeUpdate();

                // 2. Ambil data barang apa saja yang dipinjam pada transaksi ini dari rental_details
                String sqlSelectDetail = "SELECT id_barang, jumlah_pinjam FROM rental_details WHERE id_rental = ?";
                PreparedStatement pstSelectDetail = conn.prepareStatement(sqlSelectDetail);
                pstSelectDetail.setInt(1, idRental);
                ResultSet rsDetail = pstSelectDetail.executeQuery();

                // 3. Looping untuk mengembalikan stok ke tabel items
                String sqlUpdateStok = "UPDATE items SET stok = stok + ? WHERE id_barang = ?";
                PreparedStatement pstStok = conn.prepareStatement(sqlUpdateStok);

                while (rsDetail.next()) {
                    int idBarang = rsDetail.getInt("id_barang");
                    int qtyPinjam = rsDetail.getInt("jumlah_pinjam");

                    // Tambahkan (plus) stok barang sesuai jumlah yang dipinjam
                    pstStok.setInt(1, qtyPinjam);
                    pstStok.setInt(2, idBarang);
                    pstStok.executeUpdate();
                }

                // 4. Catat riwayat pengembalian ke tabel returns
                String sqlReturn = "INSERT INTO returns (id_rental, tgl_dikembalikan, kondisi_barang) VALUES (?, CURDATE(), 'Aman (Bersih)')";
                PreparedStatement pstReturn = conn.prepareStatement(sqlReturn);
                pstReturn.setInt(1, idRental);
                pstReturn.executeUpdate();

                // 5. Simpan semua perubahan secara permanen (Commit)
                conn.commit();
                JOptionPane.showMessageDialog(this, "Pengembalian barang berhasil!\nStatus menjadi 'Selesai' dan Stok telah ditambahkan kembali.");

                // Refresh ulang tabel agar data yang sudah selesai menghilang dari list
                tampilDataDipinjam();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memproses pengembalian: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusRentalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusRental;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane scrHapusRental;
    private javax.swing.JPanel tableContainer;
    private javax.swing.JTable tblHapusRental;
    // End of variables declaration//GEN-END:variables
}
