/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.customer;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import config.DatabaseConfig;

/**
 *
 * @author x395
 */
public class AddDataCustomer extends javax.swing.JFrame {
    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddDataCustomer.class.getName());

    /**
     * Creates new form AddDataCustomer
     */
    public AddDataCustomer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        getContentPane().setBackground(new java.awt.Color(115, 147, 126));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustTitle = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        fullNameInput = new javax.swing.JTextField();
        phoneNumInput = new javax.swing.JTextField();
        phoneNumLabel = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addCustButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addCustTitle.setBackground(new java.awt.Color(248, 255, 252));
        addCustTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCustTitle.setForeground(new java.awt.Color(248, 255, 252));
        addCustTitle.setText("Tambahkan Customer");

        fullNameLabel.setBackground(new java.awt.Color(248, 255, 252));
        fullNameLabel.setForeground(new java.awt.Color(248, 255, 252));
        fullNameLabel.setText("Nama Lengkap");

        fullNameInput.setBackground(new java.awt.Color(248, 255, 252));

        phoneNumInput.setBackground(new java.awt.Color(248, 255, 252));
        phoneNumInput.addActionListener(this::phoneNumInputActionPerformed);

        phoneNumLabel.setBackground(new java.awt.Color(248, 255, 252));
        phoneNumLabel.setForeground(new java.awt.Color(248, 255, 252));
        phoneNumLabel.setText("Nomor HP");

        addressInput.setBackground(new java.awt.Color(248, 255, 252));
        addressInput.addActionListener(this::addressInputActionPerformed);

        addressLabel.setBackground(new java.awt.Color(248, 255, 252));
        addressLabel.setForeground(new java.awt.Color(248, 255, 252));
        addressLabel.setText("Alamat");

        addCustButton.setBackground(new java.awt.Color(206, 185, 146));
        addCustButton.setForeground(new java.awt.Color(0, 0, 0));
        addCustButton.setText("Tambah");
        addCustButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustButtonMouseClicked(evt);
            }
        });
        addCustButton.addActionListener(this::addCustButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addressInput)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneNumInput)
                                .addComponent(phoneNumLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fullNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(addCustButton, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(addCustTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addCustTitle)
                .addGap(18, 18, 18)
                .addComponent(fullNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(addCustButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumInputActionPerformed

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressInputActionPerformed

    private void addCustButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustButtonActionPerformed
        // TODO add your handling code here:
        String newFullName = fullNameInput.getText().trim();
        String newPhoneNum = phoneNumInput.getText().trim();
        String newAddress  = addressInput.getText().trim();

        // Validasi input kosong
        if (newFullName.isEmpty() || newPhoneNum.isEmpty() || newAddress.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
            return;
        }

        String sql = "INSERT INTO customers (nama_lengkap, no_hp, alamat) VALUES (?, ?, ?)";
        try {
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, newFullName);
            ps.setString(2, newPhoneNum);
            ps.setString(3, newAddress);
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(null, "Customer " + newFullName + " telah ditambahkan!");
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_addCustButtonActionPerformed

    private void addCustButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddDataCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustButton;
    private javax.swing.JLabel addCustTitle;
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField fullNameInput;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField phoneNumInput;
    private javax.swing.JLabel phoneNumLabel;
    // End of variables declaration//GEN-END:variables
}
