/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.customer;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import config.DatabaseConfig;
/**
 *
 * @author x395
 */


public class Customer extends javax.swing.JFrame {
    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Customer.class.getName());

    /**
     * Creates new form Customer
     */
    
    public Customer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        showAllCustomers();
        getContentPane().setBackground(new java.awt.Color(115, 147, 126));

        // Warna baris tabel
        customerList.setBackground(new java.awt.Color(240, 240, 240));
        customerList.setForeground(java.awt.Color.BLACK);

        
        customerList.setSelectionBackground(new java.awt.Color(249,237,213));
        customerList.setSelectionForeground(new java.awt.Color(0,0,0));
    }
    
    private void showAllCustomers() {
        try {
            String sql = "SELECT * FROM customers ORDER BY id_customer ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            };

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_customer"),
                    rs.getString("nama_lengkap"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                });
            }

            customerList.setModel(model);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JTable();
        customerTitle = new javax.swing.JLabel();
        addCustomer = new javax.swing.JButton();
        showCustomer = new javax.swing.JButton();
        editCustomer = new javax.swing.JButton();
        deleteCustomer = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchBarInput = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 102));

        customerList.setBackground(new java.awt.Color(248, 255, 252));
        customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customerList);

        customerTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(248, 255, 252));
        customerTitle.setText("Data Customer AdventureRent");

        addCustomer.setBackground(new java.awt.Color(206, 185, 146));
        addCustomer.setForeground(new java.awt.Color(0, 0, 0));
        addCustomer.setText("Tambah Customer");
        addCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerMouseClicked(evt);
            }
        });

        showCustomer.setBackground(new java.awt.Color(206, 185, 146));
        showCustomer.setForeground(new java.awt.Color(0, 0, 0));
        showCustomer.setText("Refresh");
        showCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCustomerMouseClicked(evt);
            }
        });

        editCustomer.setBackground(new java.awt.Color(206, 185, 146));
        editCustomer.setForeground(new java.awt.Color(0, 0, 0));
        editCustomer.setText("Edit Data Customer");
        editCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerMouseClicked(evt);
            }
        });

        deleteCustomer.setBackground(new java.awt.Color(206, 185, 146));
        deleteCustomer.setForeground(new java.awt.Color(0, 0, 0));
        deleteCustomer.setText("Hapus Customer");
        deleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerMouseClicked(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(206, 185, 146));
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("Cari");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        searchBarInput.setBackground(new java.awt.Color(248, 255, 252));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(248, 255, 252));
        searchLabel.setText("Cari customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(searchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(deleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customerTitle)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(customerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCustomer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerMouseClicked
        // TODO add your handling code here:
        new AddDataCustomer().setVisible(true);
    }//GEN-LAST:event_addCustomerMouseClicked

    private void showCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCustomerMouseClicked
        // TODO add your handling code here:
        showAllCustomers();
    }//GEN-LAST:event_showCustomerMouseClicked

    private void editCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerMouseClicked
        // TODO add your handling code here:
        new EditDataCustomer().setVisible(true);
    }//GEN-LAST:event_editCustomerMouseClicked

    private void deleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerMouseClicked
        // TODO add your handling code here:
        new DeleteDataCustomer().setVisible(true);
    }//GEN-LAST:event_deleteCustomerMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        String keyword = searchBarInput.getText().trim();

        DefaultTableModel data = new DefaultTableModel(
            new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        customerList.setModel(data);

        String searchQuery = "SELECT * FROM customers WHERE " + "CAST(id_customer AS CHAR) LIKE '%" + keyword + "%' OR " + "nama_lengkap LIKE '%" + keyword + "%' OR " + "no_hp LIKE '%" + keyword + "%' OR " + "alamat LIKE '%" + keyword + "%'";
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(searchQuery);
            boolean found = false;
            while (rs.next()) {
                data.addRow(new Object[]{
                    rs.getInt("id_customer"),    
                    rs.getString("nama_lengkap"), 
                    rs.getString("no_hp"),        
                    rs.getString("alamat")        
                });
                found = true;
            }
            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Oops, data tidak ditemukan");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Customer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomer;
    private javax.swing.JTable customerList;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JButton editCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBarInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton showCustomer;
    // End of variables declaration//GEN-END:variables
}
