/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.customer;

import java.sql.Connection;
import config.DatabaseConfig;
/**
 *
 * @author x395
 */
public class DeleteDataCustomer extends javax.swing.JFrame {
    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeleteDataCustomer.class.getName());

    /**
     * Creates new form DeleteDataCustomer
     */
    public DeleteDataCustomer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        getContentPane().setBackground(new java.awt.Color(115, 147, 126));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deleteCustTitle = new javax.swing.JLabel();
        idToDeleteLabel = new javax.swing.JLabel();
        idToDeleteInput = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        deleteCustTitle.setBackground(new java.awt.Color(248, 255, 252));
        deleteCustTitle.setForeground(new java.awt.Color(248, 255, 252));
        deleteCustTitle.setText("Hapus Data Customer");

        idToDeleteLabel.setBackground(new java.awt.Color(248, 255, 252));
        idToDeleteLabel.setForeground(new java.awt.Color(248, 255, 252));
        idToDeleteLabel.setText("Masukan ID customer yang akan dihapus");

        idToDeleteInput.setBackground(new java.awt.Color(248, 255, 252));

        deleteButton.setBackground(new java.awt.Color(206, 185, 146));
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Hapus");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(deleteCustTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idToDeleteLabel)
                                .addComponent(idToDeleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(deleteCustTitle)
                .addGap(29, 29, 29)
                .addComponent(idToDeleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idToDeleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String idText = idToDeleteInput.getText().trim();

        if (idText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID tidak boleh kosong!");
            return;
        }

        int id;
        try {
            id = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
            return;
        }

        // Cek dulu apakah customer dengan ID itu ada
        String checkSql = "SELECT nama_lengkap FROM customers WHERE id_customer = ?";
        try {
            java.sql.PreparedStatement checkPs = conn.prepareStatement(checkSql);
            checkPs.setInt(1, id);
            java.sql.ResultSet rs = checkPs.executeQuery();

            if (!rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Customer dengan ID " + id + " tidak ditemukan!");
                return;
            }

            String nama = rs.getString("nama_lengkap");

            // Konfirmasi sebelum hapus
            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus customer:\n\"" + nama + "\" (ID: " + id + ")?",
                "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);
            if (konfirmasi != javax.swing.JOptionPane.YES_OPTION) return;

            // Hapus
            String deleteSql = "DELETE FROM customers WHERE id_customer = ?";
            java.sql.PreparedStatement deletePs = conn.prepareStatement(deleteSql);
            deletePs.setInt(1, id);
            deletePs.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Customer \"" + nama + "\" berhasil dihapus!");
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeleteDataCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel deleteCustTitle;
    private javax.swing.JTextField idToDeleteInput;
    private javax.swing.JLabel idToDeleteLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
