/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.customer;

import java.sql.Connection;
import config.DatabaseConfig;
/**
 *
 * @author x395
 */
public class EditThisCustomer extends javax.swing.JFrame {
    private int customerId;
    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditThisCustomer.class.getName());

    /**
     * Creates new form EditThisCustomer
     */
    public EditThisCustomer(int id, String nama, String noHp, String alamat) {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(115, 147, 126));
        this.customerId = id;
        conn = DatabaseConfig.getConnection();
        
 
        jLabel1.setText("Edit Customer ID: " + id);
        editFullNameInput.setText(nama);
        editPhoneNumInput.setText(noHp);
        editAddressInput.setText(alamat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editFullNameLabel = new javax.swing.JLabel();
        editFullNameInput = new javax.swing.JTextField();
        editPhoneNumLabel = new javax.swing.JLabel();
        editPhoneNumInput = new javax.swing.JTextField();
        editAddressInput = new javax.swing.JTextField();
        EditAddressLabel = new javax.swing.JLabel();
        saveEditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editFullNameLabel.setBackground(new java.awt.Color(248, 255, 252));
        editFullNameLabel.setForeground(new java.awt.Color(248, 255, 252));
        editFullNameLabel.setText("Nama Lengkap");

        editFullNameInput.setBackground(new java.awt.Color(248, 255, 252));
        editFullNameInput.addActionListener(this::editFullNameInputActionPerformed);

        editPhoneNumLabel.setBackground(new java.awt.Color(248, 255, 252));
        editPhoneNumLabel.setForeground(new java.awt.Color(248, 255, 252));
        editPhoneNumLabel.setText("Nomor HP");

        editPhoneNumInput.setBackground(new java.awt.Color(248, 255, 252));
        editPhoneNumInput.addActionListener(this::editPhoneNumInputActionPerformed);

        editAddressInput.setBackground(new java.awt.Color(248, 255, 252));
        editAddressInput.addActionListener(this::editAddressInputActionPerformed);

        EditAddressLabel.setBackground(new java.awt.Color(248, 255, 252));
        EditAddressLabel.setForeground(new java.awt.Color(248, 255, 252));
        EditAddressLabel.setText("Alamat");

        saveEditButton.setBackground(new java.awt.Color(206, 185, 146));
        saveEditButton.setForeground(new java.awt.Color(0, 0, 0));
        saveEditButton.setText("Simpan Perubahan");
        saveEditButton.addActionListener(this::saveEditButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveEditButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editFullNameLabel)
                        .addComponent(editFullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPhoneNumLabel)
                        .addComponent(editPhoneNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditAddressLabel)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editFullNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editFullNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editPhoneNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPhoneNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(saveEditButton)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editFullNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFullNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFullNameInputActionPerformed

    private void editPhoneNumInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPhoneNumInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPhoneNumInputActionPerformed

    private void editAddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editAddressInputActionPerformed

    private void saveEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditButtonActionPerformed
        // TODO add your handling code here:
        String nama   = editFullNameInput.getText().trim();
        String noHp   = editPhoneNumInput.getText().trim();
        String alamat = editAddressInput.getText().trim();

        if (nama.isEmpty() || noHp.isEmpty() || alamat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
            return;
        }

        String sql = "UPDATE customers SET nama_lengkap=?, no_hp=?, alamat=? WHERE id_customer=?";
        try {
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setString(2, noHp);
            ps.setString(3, alamat);
            ps.setInt(4, customerId);
            ps.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(this, "Data customer berhasil diupdate!");
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_saveEditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditThisCustomer(0, "", "", "").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditAddressLabel;
    private javax.swing.JTextField editAddressInput;
    private javax.swing.JTextField editFullNameInput;
    private javax.swing.JLabel editFullNameLabel;
    private javax.swing.JTextField editPhoneNumInput;
    private javax.swing.JLabel editPhoneNumLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveEditButton;
    // End of variables declaration//GEN-END:variables
}
