/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modules.customer;

import java.sql.Connection;
import config.DatabaseConfig;
/**
 *
 * @author x395
 */
public class EditDataCustomer extends javax.swing.JFrame {
    private Connection conn;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditDataCustomer.class.getName());

    /**
     * Creates new form EditDataCustomer
     */
    public EditDataCustomer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        getContentPane().setBackground(new java.awt.Color(115, 147, 126));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idSelectTitle = new javax.swing.JLabel();
        idSelectLabel = new javax.swing.JLabel();
        idSelectInput = new javax.swing.JTextField();
        idSelectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idSelectTitle.setBackground(new java.awt.Color(248, 255, 252));
        idSelectTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idSelectTitle.setForeground(new java.awt.Color(248, 255, 252));
        idSelectTitle.setText("Edit Data Customer");

        idSelectLabel.setBackground(new java.awt.Color(248, 255, 252));
        idSelectLabel.setForeground(new java.awt.Color(248, 255, 252));
        idSelectLabel.setText("Masukan ID Customer yang akan di edt");

        idSelectInput.setBackground(new java.awt.Color(248, 255, 252));

        idSelectButton.setBackground(new java.awt.Color(206, 185, 146));
        idSelectButton.setForeground(new java.awt.Color(0, 0, 0));
        idSelectButton.setText("Edt");
        idSelectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idSelectButtonMouseClicked(evt);
            }
        });
        idSelectButton.addActionListener(this::idSelectButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(idSelectTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idSelectLabel)
                            .addComponent(idSelectInput, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idSelectButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(idSelectTitle)
                .addGap(18, 18, 18)
                .addComponent(idSelectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idSelectInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idSelectButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSelectButtonActionPerformed
        // TODO add your handling code here:
        String idText = idSelectInput.getText().trim();

        if (idText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID tidak boleh kosong!");
            return;
        }

        int id;
        try {
            id = Integer.parseInt(idText);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
            return;
        }

        // Cari customer by ID
        String sql = "SELECT * FROM customers WHERE id_customer = ?";
        try {
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                // Customer ditemukan, buka form edit sambil kirim datanya
                String nama   = rs.getString("nama_lengkap");
                String noHp   = rs.getString("no_hp");
                String alamat = rs.getString("alamat");

                EditThisCustomer editForm = new EditThisCustomer(id, nama, noHp, alamat);
                editForm.setVisible(true);
                this.dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Customer dengan ID " + id + " tidak ditemukan!");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_idSelectButtonActionPerformed

    private void idSelectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idSelectButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idSelectButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditDataCustomer().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton idSelectButton;
    private javax.swing.JTextField idSelectInput;
    private javax.swing.JLabel idSelectLabel;
    private javax.swing.JLabel idSelectTitle;
    // End of variables declaration//GEN-END:variables
}
