/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modules.customer;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import config.DatabaseConfig;

/**
 *
 * @author x395
 */
public class pnlCustomer extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form pnlCustomer
     */
    public pnlCustomer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        showAllCustomers();
    }
    
    private void styleTable(javax.swing.JTable table) {
        // 1. Styling Baris dan Grid (Tampilan Clean/Flat)
        table.setRowHeight(35); // Bikin baris lebih tinggi agar tidak sempit
        table.setShowVerticalLines(false); // Hilangkan garis vertikal
        table.setShowHorizontalLines(true); // Biarkan garis horizontal sebagai pemisah
        table.setGridColor(new java.awt.Color(230, 230, 230)); // Warna garis horizontal abu-abu tipis
        table.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // 2. Warna saat baris diklik (Hijau Muda)
        table.setSelectionBackground(new java.awt.Color(204, 255, 204)); 
        table.setSelectionForeground(new java.awt.Color(0, 0, 0)); // Teks tetap hitam saat dipilih

        // 3. Styling Header (Warna hijau gelap sesuai tema UI-mu)
        javax.swing.table.JTableHeader header = table.getTableHeader();
        header.setBackground(new java.awt.Color(21, 100, 60)); // Background hijau
        header.setForeground(java.awt.Color.BLACK); // Teks putih
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); // Font modern

        // Bikin header lebih tinggi sedikit
        header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));

        // Rata tengah untuk teks header
        ((javax.swing.table.DefaultTableCellRenderer)header.getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.JLabel.CENTER);

        // Opsional: Membuat isi sel tabel rata tengah
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( javax.swing.JLabel.CENTER );
        for(int x=0; x < table.getColumnCount(); x++){
             table.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
    }
    }
    
    private void showAllCustomers() {
        if (conn == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Koneksi database gagal!\n\n"
                + "1. Pastikan XAMPP/MySQL sudah nyala\n"
                + "2. Database 'db_rental_camping' sudah dibuat\n"
                + "3. File lib/mysql-connector-j-9.6.0.jar ada di project",
                "Koneksi Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "SELECT * FROM customers ORDER BY id_customer ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            };

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_customer"),
                    rs.getString("nama_lengkap"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                });
            }

            customerList.setModel(model);
            styleTable(customerList);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        customerTitle = new javax.swing.JLabel();
        searchBarInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JTable();
        addCustomer = new javax.swing.JButton();
        showCustomer = new javax.swing.JButton();
        editCustomer = new javax.swing.JButton();
        deleteCustomer = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(115, 147, 126));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(248, 255, 252));
        searchLabel.setText("Cari customer");

        customerTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(248, 255, 252));
        customerTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerTitle.setText("Data Customer AdventureRent");
        customerTitle.setToolTipText("");

        searchBarInput.setBackground(new java.awt.Color(248, 255, 252));

        searchButton.setBackground(new java.awt.Color(206, 185, 146));
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("Cari");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        customerList.setBackground(new java.awt.Color(248, 255, 252));
        customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(customerList);

        addCustomer.setBackground(new java.awt.Color(206, 185, 146));
        addCustomer.setForeground(new java.awt.Color(0, 0, 0));
        addCustomer.setText("Tambah Customer");
        addCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerMouseClicked(evt);
            }
        });
        addCustomer.addActionListener(this::addCustomerActionPerformed);

        showCustomer.setBackground(new java.awt.Color(206, 185, 146));
        showCustomer.setForeground(new java.awt.Color(0, 0, 0));
        showCustomer.setText("Refresh");
        showCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showCustomerMouseClicked(evt);
            }
        });

        editCustomer.setBackground(new java.awt.Color(206, 185, 146));
        editCustomer.setForeground(new java.awt.Color(0, 0, 0));
        editCustomer.setText("Edit Data Customer");
        editCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerMouseClicked(evt);
            }
        });

        deleteCustomer.setBackground(new java.awt.Color(206, 185, 146));
        deleteCustomer.setForeground(new java.awt.Color(0, 0, 0));
        deleteCustomer.setText("Hapus Customer");
        deleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(showCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(customerTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(customerTitle)
                    .addGap(16, 16, 16)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchButton)
                        .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(addCustomer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(showCustomer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editCustomer)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteCustomer))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        String keyword = searchBarInput.getText().trim();
        if (conn == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Koneksi database gagal!");
            return;
        }

        DefaultTableModel data = new DefaultTableModel(
            new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        customerList.setModel(data);
        styleTable(customerList);

        String searchQuery = "SELECT * FROM customers WHERE " + "CAST(id_customer AS CHAR) LIKE '%" + keyword + "%' OR " + "nama_lengkap LIKE '%" + keyword + "%' OR " + "no_hp LIKE '%" + keyword + "%' OR " + "alamat LIKE '%" + keyword + "%'";
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(searchQuery);
            boolean found = false;
            while (rs.next()) {
                data.addRow(new Object[]{
                    rs.getInt("id_customer"),
                    rs.getString("nama_lengkap"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                });
                found = true;
            }
            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Oops, data tidak ditemukan");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void addCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerMouseClicked
        // TODO add your handling code here:
        new AddDataCustomer().setVisible(true);
    }//GEN-LAST:event_addCustomerMouseClicked

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerActionPerformed

    private void showCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showCustomerMouseClicked
        // TODO add your handling code here:
        showAllCustomers();
    }//GEN-LAST:event_showCustomerMouseClicked

    private void editCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerMouseClicked
        // TODO add your handling code here:
        new EditDataCustomer().setVisible(true);
    }//GEN-LAST:event_editCustomerMouseClicked

    private void deleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerMouseClicked
        // TODO add your handling code here:
        new DeleteDataCustomer().setVisible(true);
    }//GEN-LAST:event_deleteCustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomer;
    private javax.swing.JTable customerList;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JButton editCustomer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBarInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton showCustomer;
    // End of variables declaration//GEN-END:variables
}
