/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modules.customer;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import config.DatabaseConfig;

/**
 *
 * @author x395
 */
public class pnlCustomer extends javax.swing.JPanel {
    private Connection conn;
    /**
     * Creates new form pnlCustomer
     */
    public pnlCustomer() {
        initComponents();
        conn = DatabaseConfig.getConnection();
        showAllCustomers();
    }
    
    private void styleTable(javax.swing.JTable table) {
        // 1. Styling Baris dan Grid (Tampilan Clean/Flat)
        table.setRowHeight(35); // Bikin baris lebih tinggi agar tidak sempit
        table.setShowVerticalLines(false); // Hilangkan garis vertikal
        table.setShowHorizontalLines(true); // Biarkan garis horizontal sebagai pemisah
        table.setGridColor(new java.awt.Color(230, 230, 230)); // Warna garis horizontal abu-abu tipis
        table.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        // 2. Warna saat baris diklik (Hijau Muda)
        table.setSelectionBackground(new java.awt.Color(204, 255, 204)); 
        table.setSelectionForeground(new java.awt.Color(0, 0, 0)); // Teks tetap hitam saat dipilih

        // 3. Styling Header (Warna hijau gelap sesuai tema UI-mu)
        javax.swing.table.JTableHeader header = table.getTableHeader();
        header.setBackground(new java.awt.Color(21, 100, 60)); // Background hijau
        header.setForeground(java.awt.Color.BLACK); // Teks putih
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); // Font modern

        // Bikin header lebih tinggi sedikit
        header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));

        // Rata tengah untuk teks header
        ((javax.swing.table.DefaultTableCellRenderer)header.getDefaultRenderer())
                .setHorizontalAlignment(javax.swing.JLabel.CENTER);

        // Opsional: Membuat isi sel tabel rata tengah
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( javax.swing.JLabel.CENTER );
        for(int x=0; x < table.getColumnCount(); x++){
             table.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
    }
    }
    
    private void showAllCustomers() {
        if (conn == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Koneksi database gagal!\n\n"
                + "1. Pastikan XAMPP/MySQL sudah nyala\n"
                + "2. Database 'db_rental_camping' sudah dibuat\n"
                + "3. File lib/mysql-connector-j-9.6.0.jar ada di project",
                "Koneksi Gagal", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "SELECT * FROM customers ORDER BY id_customer ASC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel model = new DefaultTableModel(
                new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
            ) {
                @Override
                public boolean isCellEditable(int row, int col) { return false; }
            };

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_customer"),
                    rs.getString("nama_lengkap"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                });
            }

            customerList.setModel(model);
            styleTable(customerList);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        customerTitle = new javax.swing.JLabel();
        searchBarInput = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerList = new javax.swing.JTable();
        addCustomer = new javax.swing.JButton();
        editCustomer = new javax.swing.JButton();
        deleteCustomer = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(115, 147, 126));

        searchLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(248, 255, 252));
        searchLabel.setText("Cari customer");

        customerTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customerTitle.setForeground(new java.awt.Color(248, 255, 252));
        customerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerTitle.setText("Data Customer AdventureRent");

        searchBarInput.setBackground(new java.awt.Color(248, 255, 252));

        searchButton.setBackground(new java.awt.Color(206, 185, 146));
        searchButton.setText("Cari");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        customerList.setBackground(new java.awt.Color(248, 255, 252));
        customerList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerList);

        addCustomer.setBackground(new java.awt.Color(206, 185, 146));
        addCustomer.setText("Tambah");
        addCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerMouseClicked(evt);
            }
        });
        addCustomer.addActionListener(this::addCustomerActionPerformed);

        editCustomer.setBackground(new java.awt.Color(206, 185, 146));
        editCustomer.setText("Edit");
        editCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCustomerMouseClicked(evt);
            }
        });

        deleteCustomer.setBackground(new java.awt.Color(206, 185, 146));
        deleteCustomer.setText("Hapus");
        deleteCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCustomerMouseClicked(evt);
            }
        });
        deleteCustomer.addActionListener(this::deleteCustomerActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                        .addComponent(customerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(addCustomer)
                    .addComponent(editCustomer)
                    .addComponent(searchButton)
                    .addComponent(searchBarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCustomer))
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(customerTitle)
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        String keyword = searchBarInput.getText().trim();

        DefaultTableModel data = new DefaultTableModel(
            new String[]{"ID", "Nama Lengkap", "No HP", "Alamat"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int col) { return false; }
        };
        customerList.setModel(data);
        styleTable(customerList);

        String searchQuery = "SELECT * FROM customers WHERE " + "CAST(id_customer AS CHAR) LIKE '%" + keyword + "%' OR " + "nama_lengkap LIKE '%" + keyword + "%' OR " + "no_hp LIKE '%" + keyword + "%' OR " + "alamat LIKE '%" + keyword + "%'";
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(searchQuery);
            boolean found = false;
            while (rs.next()) {
                data.addRow(new Object[]{
                    rs.getInt("id_customer"),
                    rs.getString("nama_lengkap"),
                    rs.getString("no_hp"),
                    rs.getString("alamat")
                });
                found = true;
            }
            if (!found) {
                javax.swing.JOptionPane.showMessageDialog(null,
                    "Oops, data tidak ditemukan");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void customerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerListMouseClicked

        int baris = customerList.getSelectedRow();
        System.out.println("Baris yang terpilih: " + baris); // Tambahkan baris ini

        // 2. Pastikan ada baris yang valid diklik (bukan area kosong)
        if (baris != -1) {
            try {
                // 3. Ambil data dari tabel berdasarkan urutan kolom.
                // PENTING: Sesuaikan angka 0, 1, 2, 3 dengan urutan kolom di desain JTable kamu!
                // Misalnya: 0 = ID, 1 = Nama, 2 = No HP, 3 = Alamat

                String idString = customerList.getValueAt(baris, 0).toString();
                int idCust = Integer.parseInt(idString); // Konversi ID menjadi integer

                String namaCust = customerList.getValueAt(baris, 1).toString();
                String noHpCust = customerList.getValueAt(baris, 2).toString();
                String alamatCust = customerList.getValueAt(baris, 3).toString();

                // 4. Panggil JFrame EditThisCustomer dan lempar datanya ke dalam constructor
                EditThisCustomer editFrame = new EditThisCustomer(idCust, namaCust, noHpCust, alamatCust);

                // 5. Tampilkan jendela edit
                editFrame.setVisible(true);

                // 6. (Fitur Tambahan) Refresh tabel otomatis saat jendela edit ditutup
                editFrame.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                        // Panggil method untuk memuat ulang isi tabel dari database
                        // Contoh jika nama methodmu loadData() atau tampilkanData()
                        // loadData();
                    }
                });

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Format ID tidak valid: " + e.getMessage());
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_customerListMouseClicked

    private void addCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerMouseClicked
        // TODO add your handling code here:
        new AddDataCustomer().setVisible(true);
    }//GEN-LAST:event_addCustomerMouseClicked

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerActionPerformed

    private void editCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCustomerMouseClicked
        System.out.println("BABBABBA");
    }//GEN-LAST:event_editCustomerMouseClicked

    private void deleteCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCustomerMouseClicked
        // TODO add your handling code here:
        new DeleteDataCustomer().setVisible(true);
    }//GEN-LAST:event_deleteCustomerMouseClicked

    private void deleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomer;
    private javax.swing.JTable customerList;
    private javax.swing.JLabel customerTitle;
    private javax.swing.JButton deleteCustomer;
    private javax.swing.JButton editCustomer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchBarInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    // End of variables declaration//GEN-END:variables
}
